# Generated by Django 3.0.4 on 2020-03-11 16:14

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0006_auto_20200311_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(upload_to='fotos'),
        ),
    ]
