version: '3'

services:
  django:
    build: ./django
    restart: always
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    restart: always
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./django/static:/var/www/static     # para los archivos static
      - ./django/media:/var/www/media     # para los archivos media
      - ./log/nginx/:/var/log/nginx/      
    ports:
      - "81:81"
    depends_on:
      - django
volumes:
  node-modules:
      

