# Generated by Django 3.0.3 on 2020-02-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='descripcion',
            new_name='descripción',
        ),
    ]
