# Generated by Django 3.0.4 on 2020-03-11 15:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0005_auto_20200226_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(upload_to='whatever'),
        ),
    ]
