# Generated by Django 3.0.5 on 2020-05-03 14:50

from django.db import migrations, models
import sorl.thumbnail.fields
import visitas_granada.models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_granada', '0007_auto_20200311_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='descripcion',
            field=models.CharField(max_length=1000, validators=[visitas_granada.models.validate_capitalized]),
        ),
        migrations.AlterField(
            model_name='visita',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='fotos'),
        ),
    ]
